### ISSUE TITLE
Multiples peripherals

### ISSUE THREAD

**Issue by nothing-fr** [dynasticorpheus/ws50-sync#2]
Hello,

I have a Withings Smart Body Analyzer and an Aura which mesure temperature and air quality too, is it possible to choose what device I want to sync in domoticz ?

Thanks.

**Comment by dynasticorpheus** [comment]
I assume it just a matter of selecting the correct device and the data structure would be more or less the same. Having said that .. I do not own the device so can't check I am afraid.
