### ISSUE TITLE
stopped working?

### ISSUE THREAD

**Issue by darkzbaron** [dynasticorpheus/ws50-sync#3]
I am getting a http 500 error

**Comment by dynasticorpheus** [comment]
Seems I am having the same. Let me check

**Comment by darkzbaron** [comment]
cool! Thanks for the great work!

On 9 February 2017 at 21:05, dynasticorpheus <notifications@github.com<mailto:notifications@github.com>> wrote:

Seems I am having the same. Let me check

**Comment by dynasticorpheus** [comment]
They implemented protection against cross-site request forgery (CSRF) hence a csrf_token needed to be added to the authentication request. Should be fixed through latest commit dd74fce. Please confirm this is also working on your end.

**Comment by darkzbaron** [comment]
all good. I just had to amend the requirements with lxml==3.6.0

Thanks so much!

**Comment by darkzbaron** [comment]
Hi there, I think it stopped working again. Do you have the same?

It seems like the auth is failing

**Comment by dynasticorpheus** [comment]
Still works for me?
