### ISSUE TITLE
Changes in Withings API since Nokia took over?

### ISSUE THREAD

**Issue by odelma** [dynasticorpheus/ws50-sync#5]
Hi,

I noticed there was a big change in Withings app a couple of weeks ago and around the same time the script stopped working. Perhaps they've changed thing on the api side as well? Any chance getting the script working again, or is this perhaps something that is only bothering my setup?

Not sure if this is any help (as co2/temp are still not supported in the official api): https://developer.health.nokia.com/api

**Comment by dynasticorpheus** [comment]
I was pulling the information based on the API they used on their website. The new Nokia based website lacks the CO2 & temperature information completely. Will need to investigate how this works in their app to get this working again.

**Comment by odelma** [comment]
Ok, might prove quite tricky then. I'll keep my fingers crossed...:smile: Thanks for looking into it!

**Comment by dynasticorpheus** [comment]
@odelma  I have adjusted the code. Can you please update and test at your end as well?

**Comment by odelma** [comment]
That was very fast and works great in my setup as well! Thanks a lot!

**Comment by dynasticorpheus** [comment]
Resolved through 0cebdeb

**Comment by odelma** [comment]
HI, @dynasticorpheus - I guess there's been some change again in the api. Could you perhaps take a look if it would be something easy to fix?  😀
